server:
  port: 8080

redis:
  host: 127.0.0.1
  port: 6379  
  password: 
  timeout: 10000
# pool
  maxActive: 200
  maxWait: 1
  maxIdle: 8
  minIdle: 0

spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chtest
    username: root
    password: 123456
  jpa:
  # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true